Qshop/Buyer/urls.py
from django.urls import path,include
from .views import *

urlpatterns = [
    path("index/",index),
    path("login/",login),
    path("register/",register),
    path("logout/",logout),
    path("goods_list/",goods_list),
    path("goods_detail/",goods_detail),
    path("place_order/",place_order),
    path("alipay_order/",alipay_order),
    path("pay_result/",pay_result),
    path("cart/",cart),
    path("add_cart/",add_cart),
    path("change_cart/",change_cart),
    path("cart_place_order/",cart_place_order),
    path("user_center_order/",user_center_order),
    path("get_cachegoods/",get_cachegoods),
    path("update_cachegoods/",update_cachegoods),
    path("user_center_info/",user_center_info),
    path("user_center_site/",user_center_site),
    path("update_useraddress/",update_useraddress),
]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from Buyer.views import index,login,register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seller/',include("Seller.urls")),
    path('buyer/',include("Buyer.urls")),
    re_path("^$",index),
    path('login/',login),
    path('register/',register),
]

Qshop/Buyer/models.py
from django.db import models
from Seller.models import LoginUser,Goods

# Create your models here.

ORDER_STATUS = (
    (1,"未支付"),
    (2,"已支付"),
    (3,"待发货"),
    (4,"已发货"),
    (5,"拒收"),
    (6,"已完成"),
)
class PayOrder(models.Model):
    order_number = models.CharField(max_length=36,unique=True,verbose_name="订单号")
    order_date = models.DateField(auto_now=True,verbose_name="订单创建时间")
    order_status = models.IntegerField(choices=ORDER_STATUS,verbose_name="订单状态")
    order_total = models.FloatField(verbose_name="订单总价")
    order_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="买家")
    class Meta:
        db_table = "pay_order"

class OrderInfo(models.Model):
    order = models.ForeignKey(to=PayOrder,on_delete=models.CASCADE)
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    goods_price = models.FloatField(verbose_name="商品的单价")
    store = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="卖家")
    goods_count = models.IntegerField(verbose_name="购买的单品的数量")
    goods_total_price = models.FloatField(verbose_name="购买的单品的总金额")
    class Meta:
        db_table = "order_info"


class Cart(models.Model):
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    goods_number = models.IntegerField(verbose_name="商品的数量")
    goods_total = models.FloatField(verbose_name="商品的小计")
    # goods_price = models.FloatField()
    cart_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="买家")
    class Meta:
        db_table = "cart"

class UserAddress(models.Model):
    name = models.CharField(max_length=32,verbose_name="收货人姓名")
    phone = models.CharField(max_length=11,verbose_name="收货人手机号")
    address = models.TextField(verbose_name="收货人手机号")
    user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)
    status = models.IntegerField(verbose_name="地址状态",default=0)  ### 1 为使用中  0为 未使用

class PayorderAddress(models.Model):
    name = models.CharField(max_length=32,verbose_name="收货人姓名")
    phone = models.CharField(max_length=11,verbose_name="收货人手机号")
    address = models.TextField(verbose_name="收货人手机号")
    payorder = models.OneToOneField(to=PayOrder,on_delete=models.CASCADE)  ## 一对一

Qshop/Buyer/views.py
from django.shortcuts import render
import hashlib
from django.http import HttpResponseRedirect,JsonResponse
from Seller.models import LoginUser,GoodsType,Goods
from .models import PayOrder,OrderInfo,Cart,UserAddress,PayorderAddress



# Create your views here.
## 密码加密
def setPassword(password):
    md5 = hashlib.md5()
    md5.update(password.encode())
    result = md5.hexdigest()
    return result
## 登录装饰器
def loginValid(func):
    def inner(request,*args,**kwargs):
        ##校验登录
        cookie_email = request.COOKIES.get("buy_email")
        session_email = request.session.get("buy_email")
        if cookie_email and session_email and cookie_email == session_email:
            flag = LoginUser.objects.filter(email=cookie_email,id=request.COOKIES.get("buy_userid"),user_type=1).exists()
            if flag:
                return func(request,*args,**kwargs)
            else:
                return HttpResponseRedirect("/login/")
        else:
            return HttpResponseRedirect("/login/")
    return inner


## 首页
# @loginValid
def index(request):
    """
    1、如果类型下面没有商品，类型不展示
    2、如果类型下面超过4个商品，应该展示4个
    3、如果类型下面商品 大于0 小于 4  应该展示商品
    """
    goods_type = GoodsType.objects.all()
    ## 处理返回的数据  构建数据
    ## res = [{"type":"新鲜水果.obj","goods":[goods1,goods2,goods3,goods4]},{},{}]
    res = []
    for one in goods_type:
        goods = one.goods_set.order_by("id").all()
        if len(goods) > 4:
            goods_list = goods[:4]
            res.append({"type":one,"goods_list":goods_list})
        elif len(goods) > 0 and len(goods) <= 4:
            goods_list = goods
            res.append({"type": one, "goods_list": goods_list})

    return render(request,"buyer/index.html",locals())
def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("pwd")
        if username and password:
            user = LoginUser.objects.filter(username=username,password=setPassword(password),user_type=1).first()
            if user:
                ## 成功登录
                response = HttpResponseRedirect("/")
                response.set_cookie("buy_email",user.email)
                response.set_cookie("buy_username",user.username)
                response.set_cookie("buy_userid",user.id)
                request.session["buy_email"] = user.email
                return response
            else:
                message = "账号密码不正确"
        else:
            message = "参数为空"

    return render(request,"buyer/login.html",locals())
def register(request):
    ## 接收参数
    if request.method == "POST":
        username = request.POST.get("user_name")
        password = request.POST.get("pwd")
        repassword = request.POST.get("cpwd")
        email = request.POST.get("email")
        ## 校验数据
        if email and password and password == repassword:
            ## 有数据
            LoginUser.objects.create(email=email,password=setPassword(password),username=username)
            return HttpResponseRedirect("/login/")
        else:
            ## 参数为空
            message = "参数为空"

    return render(request,"buyer/register.html")

def logout(request):
    resp =  HttpResponseRedirect("/login/")
    resp.delete_cookie("buy_email")
    resp.delete_cookie("buy_username")
    resp.delete_cookie("buy_userid")
    del request.session["buy_email"]
    return resp


def base(request):
    return render(request,"buyer/base.html")

## 商品列表页面
def goods_list(request):
    kywards = request.GET.get("kywards")
    req_type = request.GET.get("req_type")
    ## 判断请求的方式
    if req_type == "find_all":
        ## 查看更多
            ## kywards 应该为 类型的id
        goods_type = GoodsType.objects.filter(id = int(kywards)).first()
        goods = goods_type.goods_set.order_by("-goods_pro_time")

    else:
        ## 搜索
            ## kywards 应该为 商品的名字
            ## 模糊查询
        goods = Goods.objects.filter(goods_name__contains= kywards).order_by("-goods_pro_time")
    goods_new = goods[:2]
    return render(request,"buyer/goods_list.html",locals())




## 商品详情页
def goods_detail(request):
    ##  通过商品的id 获取商品
    goods_id = request.GET.get("goods_id")
    goods = Goods.objects.get(id= int(goods_id))
    return render(request,"buyer/goods_detail.html",locals())

def get_order_no():
    import uuid
    order_no = str(uuid.uuid4()).replace("-","")
    return order_no
## 订单页面
@loginValid
def place_order(request):
    ## 保存数据
    ## 获取 买家的user_id
    user_id = request.COOKIES.get("buy_userid")
    goods_id = request.GET.get("goods_id")
    goods_count = int(request.GET.get("goods_count"))
    ## 查找商品
    goods = Goods.objects.get(id=goods_id)
    ##payorder
    payorder = PayOrder()
    payorder.order_number = get_order_no()
    payorder.order_status = 1   ### 未支付状态
    payorder.order_total = goods_count * goods.goods_price
    payorder.order_user_id = int(user_id)
    payorder.save()


    order_info = OrderInfo()
    order_info.order = payorder
    order_info.goods = goods
    order_info.goods_price = goods.goods_price
    ## 店铺的信息 通过商品寻找 店铺
    order_info.store = goods.goods_store
    order_info.goods_count = goods_count
    order_info.goods_total_price = goods_count * goods.goods_price
    order_info.save()
    user_address = UserAddress.objects.filter(user_id=user_id,status=1).first()

    ## orderinfo
    return render(request,"buyer/place_order.html",locals())


## 聚合函数
from django.db.models import Sum,Count,F,Q
def goods_test(request):
    order_id = 21
    pay_order = PayOrder.objects.get(id = order_id)
    ## 聚合方法   aggregate
    ## 返回值： 字典
    ## key 是默认的 goods_count__聚合方法
    ## 可以修改key
    sum_goods = pay_order.orderinfo_set.aggregate(Sum("goods_count"),
                                                  mycount = Count("id") )
    return render(request,"buyer/goods_test.html",locals())

from Qshop.settings import alipay
## 支付宝支付
@loginValid
def alipay_order(request):
    ## 获取订单  payorder _id
    payorder_id = request.GET.get("payorder_id")
    payorder = PayOrder.objects.get(id=payorder_id)
    ## 保存订单和地址的关系
    user_id = request.COOKIES.get("buy_userid")
    user_address = UserAddress.objects.filter(user_id=user_id,status=1).first()     ### 获取用户当前的地址
    ## 保存关系
    PayorderAddress.objects.create(name=user_address.name,
                                                      address= user_address.address,
                                                      phone=user_address.phone,
                                                      payorder=payorder)




    # 3、 实例化一个订单
    order_string = alipay.api_alipay_trade_page_pay(
        subject="生鲜交易",  ## 主题
        out_trade_no= payorder.order_number,  ## 订单号
        total_amount= str(payorder.order_total),  ## 交易金额   字符串
        return_url="http://127.0.0.1:8000/buyer/pay_result/",  ##  回调的地址
        notify_url=None  ## 通知
    )

    # 4、 返回支付宝支付的url
    result = "https://openapi.alipaydev.com/gateway.do?" + order_string
    return HttpResponseRedirect(result)

## 接收支付宝的支付结果
def pay_result(request):
    out_trade_no = request.GET.get("out_trade_no")
    ## 修改订单的状态  未付款 -》 已付款
    payorder = PayOrder.objects.get(order_number=out_trade_no)
    payorder.order_status = 2
    payorder.save()

    return render(request,"buyer/pay_result.html",locals())

from django.db.models import Sum
## 购物车
@loginValid
def cart(request):
    ## 查看 登录用户的购物车内容
    user_id = request.COOKIES.get("buy_userid")
    cart = Cart.objects.filter(cart_user=LoginUser.objects.get(id=int(user_id))).all()

    ## 获取购物车中所有商品的 小计之和 以及 商品的数量之和
    ## 聚合  all_total 字典  key：vlaue  ->  {"sum_total":3232,"sum_number":3232}
    all_total = cart.aggregate(sum_total = Sum("goods_total"),sum_number = Sum("goods_number"))

    return render(request,"buyer/cart.html",locals())

## 添加购物车
@loginValid
def add_cart(request):
    result = {"code":10000,"msg":"添加购物车成功"}
    data = request.POST
    ## 从cookie中获取买家
    user_id = request.COOKIES.get("buy_userid")
    print(data)
    goods_id = data.get("goods_id")
    goods_count = int(data.get("goods_count",1))  ## 商品详情页
    goods = Goods.objects.get(id = goods_id)

    ## 判断购物车中是否已经存在该商品
    cart = Cart.objects.filter(goods = goods).first()
    if cart:
        ## 存在
        cart.goods_number += goods_count
        # cart.goods_total = goods.goods_price * (goods_count + cart.goods_number)
        cart.goods_total += goods.goods_price * goods_count
    else:
        ## 不存在
        cart = Cart()
        cart.goods = goods
        cart.goods_number = goods_count
        cart.goods_total = goods_count * goods.goods_price
        cart.cart_user_id = user_id
    try:
        cart.save()
        result = {"code":10000,"msg":"添加购物车成功"}
    except:
        result = {"code": 10001, "msg": "添加购物车失败"}
    return JsonResponse(result)

def change_cart(request):
    result = {"code":10001,"msg":"计算失败","data":{}}
    ## 修改购物车的数量 以及小计
    ##   购物车id
    ## 操作的类型    add reduce

    data= request.POST
    print(data)
    cart_id = request.POST.get("cart_id")
    js_type = request.POST.get("js_type")
    if cart_id and js_type:
        cart = Cart.objects.filter(id = int(cart_id)).first()
        if cart:
            if js_type == "add":
                ## 加 操作
                cart.goods_number += 1
                cart.goods_total += cart.goods.goods_price
            else:
                ##减操作
                cart.goods_number -= 1
                cart.goods_total -= cart.goods.goods_price
            try:
                cart.save()
                result = {"code":10000,"msg":"操作成功","data":{"goods_number":cart.goods_number,"goods_total":cart.goods_total}}
            except:
                result = {"code":10003,"msg":"操作失败"}

        ## 将修改之后结果 返回到前端
        else:
            result = {"code": 10002, "msg": "商品不存在", "data": {}}

    return JsonResponse(result)




## 购物车 去结算
@loginValid
def cart_place_order(request):
    ## 获取购物车 id
    data = request.POST
    res = []   ### 购物车id
    for key,value in data.items():
        # print(key)

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}天天生鲜-首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
{% block style %}

{% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>{{ request.COOKIES.buy_username }}</em>
				</div>
				<div class="login_btn fl">
                    {% if request.COOKIES.buy_username %}
                        <a href="#">{{ request.COOKIES.buy_username }}</a>
					    <span>|</span>
					    <a href="/buyer/logout/">退出</a>
                    {% else %}
                        <a href="/login/">登录</a>
					    <span>|</span>
					    <a href="/register/">注册</a>
                    {% endif %}

				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/buyer/user_center_info/">用户中心</a>
					<span>|</span>
					<a href="/buyer/cart/">我的购物车</a>
					<span>|</span>
					<a href="/buyer/user_center_order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
            <form action="/buyer/goods_list/">
                <input type="text" class="input_text fl" name="kywards" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/buyer/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
    {% endblock %}

    {% block content %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
	<script type="text/javascript">
		//  BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		// oFruit.onclick = function(){
		// 	window.location.href = 'list.html';
		// }
	</script>
{% block script %}
{% endblock %}
</body>
</html>

Qshop/Buyer/templates/buyer/cart.html
{% extends "buyer/base.html" %}
{% block content %}
    	<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/buyer/cart_place_order/" method="post">
    {% csrf_token %}
    {% for one in cart %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="cart_id_{{ one.id }}" value="{{ one.id }}" checked class="goods_box"></li>
		<li class="col02"><img src="/static/{{ one.goods.goods_picture }}"></li>
		<li class="col03">{{ one.goods.goods_name }}<br><em>{{ one.goods.goods_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ one.goods.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" onclick="jisuan({{ one.id }},'add')">+</a>
				<input type="text" class="num_show fl" id="goods_num_{{ one.id }}" value="{{ one.goods_number }}">
				<a href="javascript:;" class="minus fl" onclick="jisuan({{ one.id }},'reduce')">-</a>
			</div>
		</li>
		<li class="col07" id="goods_total_{{ one.id }}">{{ one.goods_total }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked="" id="check_box"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="total_money">{{ all_total.sum_total }}</em><br>共计<b id="total_num">{{ all_total.sum_number }}</b>件商品</li>
		<li class="col04">
            <input type="submit" style="width: 150px;height: 50px;background-color: red;" value="去结算">
        </li>

	</ul>
      </form>

{% endblock %}

{% block script %}
    <script>
        $("#check_box").click(
            function () {
                // console.log(111111)
                //  input  checkbox
                //  判断 全选框 是否有checked 属性
                if (this.checked){
                    //  true  有checked 属性
                    //  将每一项 设置都有 checked 属性
                    //  prop 可以为选中的标签设置属性
                    $(".goods_box").prop("checked",true);
                    // console.log(this.checked)
                } else{
                    // false 没有checked 属性
                     //  将每一项设置都没有 checked 属性
                    $(".goods_box").prop("checked",false);
                    // console.log(this.checked)
                }
                add();

            }
        )
        $(".goods_box").click(
            function () {
                    //   单选
                //  获取所有项 的input的数量
                var len1 = $(".goods_box").length;
                // console.log(len1);
                //  获取所有项 中有checked 属性的数量
                var len2 = $(".goods_box:checked").length;
                // console.log(len2);
                //  对比两值
                if (len1 == len2){
                    // 相等    全选框增加 checked 属性
                    $("#check_box").prop("checked",true);

                }else{
                    //         全选款去掉checked 属性
                    $("#check_box").prop("checked",false);
                }
                add()
            }
        )

    function add() {
        // 方法实现  单选  全选之后  计算 总数量以及总的价格，并将结果进行设置
        // 获取到每一个没选中的 商品的 价格 以及数量
        //  进行计算   总的 价格 和数量
        //  进行设置
        // each  循环遍历
        var mydict = {"num":0,"total_money":0}
        $(".goods_box").each(
            function () {
                // 判断 有checked 属性的 标签
                if(this.checked){
                    //   寻找被选中的数量以及价格
                    // console.log(111111)
                    var number = parseInt($(this).parents(".cart_list_td").find(".num_show").val());
                    var money = parseFloat($(this).parents(".cart_list_td").find(".col07").text());
                    mydict.num += number;
                    mydict.total_money += money;
                }
            }
        )
        // console.log(mydict);
        //  设置值
        $("#total_money").text(mydict.total_money);
        $("#total_num").text(mydict.num);
    }

    function jisuan(cart_id,js_type) {

        //  ajax  将请求 发送到后端进行处理
        var url = "/buyer/change_cart/";
        var cart_id = cart_id;
        var js_type = js_type;

        send_data = {
            "csrfmiddlewaretoken":"{{ csrf_token }}",
            "cart_id":cart_id,
            "js_type":js_type,
        };
        $.ajax({
            url:url,
            type:"post",
            data:send_data,
            success:function (data) {
                console.log(data);
                if (data.code == 10000){
                    console.log(data.data["goods_number"]);
                    console.log(data.data["goods_total"]);
                    // 将数量进行设置
                    document.getElementById("goods_num_" + cart_id).value = data.data["goods_number"];
                    // 将小计进行设置
                    document.getElementById("goods_total_" + cart_id).innerHTML = data.data["goods_total"];
                    add();
                }else{
                    alert(data.msg )
                }
            },
            error:function (data) {
                console.log(data)
            }
        })

    }




    </script>
{% endblock %}

Qshop/Buyer/templates/buyer/goods_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    统计订单下面的 订单详情中商品的数量
    {{ sum_goods }}
</p>

</body>
</html>

Qshop/Buyer/templates/buyer/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/buyer/images/logo02.png"></a>	
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>

				</div>
                   <p>
                    {{ message }}
                    </p>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

Qshop/Buyer/templates/buyer/pay_result.html
{% extends "buyer/base.html" %}

{% block content %}
{#    {{ request.GET }}#}
    {% for key,value in request.GET.items %}
        <p>
            {{ key }}:{{ value }}
        </p>
    {% endfor %}
{% endblock %}

Qshop/Buyer/templates/buyer/user_center_order.html
{% extends "buyer/base.html" %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/buyer/user_center_info/">· 个人信息</a></li>
				<li><a href="/buyer/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="/buyer/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for payorderone in payorder_all %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ payorderone.order_date | date:"Y-m-d" }}</li>
                    <li class="col02 stress">{{ payorderone.get_order_status_display }}</li>
					<li class="col02" style="width: 300px;">订单号：{{ payorderone.order_number }}</li>

				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for orderinfoone in payorderone.orderinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ orderinfoone.goods.goods_picture }}"></li>
									<li class="col02">{{ orderinfoone.goods.goods_name }}<em>{{ orderinfoone.goods.goods_price }}元/500g</em></li>
									<li class="col03">{{ orderinfoone.goods_count }}</li>
									<li class="col04">{{ orderinfoone.goods_total_price }}元</li>
								</ul>
                                    {% endfor %}

							</td>
							<td width="15%">{{ payorderone.order_total }}元</td>
							<td width="15%">{{ payorderone.get_order_status_display }}</td>
							<td width="15%">
                                {% if payorderone.order_status == 1 %}
                                    <a href="/buyer/alipay_order/?payorder_id={{ payorderone.id }}" class="oper_btn">去付款</a>
                                {% else %}
                                    <a href="#" class="oper_btn">查看物流</a>
                                {% endif %}
                            </td>
						</tr>
					</tbody>
				</table>
            {% endfor %}






				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}